### ISSUE TITLE
401 and Problem in deAuth request

### ISSUE THREAD

**Issue by rubberbird** [BirdyF/strava_flutter#3]
Is this working for you? I can authenticate but getting 401 for all API functions. Also when I try a de-auth I get an error.

flutter: --> Strava_flutter: Problem in deAuthorize request
flutter: --> Strava_flutter: Problem in deAuthorize request

**Comment by BirdyF** [comment]
I published a new build (20).
- Fix problem (thanks!) in deAuthorize and oauth (was not calling newAuthorization but refreshToken)

But now even when DeAuthorize is successful (200 and access token), it is not possible to change the user, only the Strava screen showing the scope appears, not the one to enter username and psw.
I can see that the app has been removed/revoked (in settings/my apps on strava.com) but somehow Strava seems to keep track of the user.
To change user for the moment, you have to delet/desinstall the app.
Will contact Strava to check if it is normal

- Otherwise it works for me.
If you have problem please let me know:
a) if it is on iOS or Android
b) if it is the first run after install or not
c) the log given by strava_flutter (with isInDebug set to true)

**Comment by BirdyF** [comment]
I suspect it is related to the cache of the webView used to show Strava screens

**Comment by BirdyF** [comment]
I checked with Strava. It is the normal behavior. When running deAuthorize you can change the scope but you can NOT change the user.

To be able to change user, you have to desinstall the app and reinstall it.
I asked in the below issue on Flutter if it is possible to get an option in launch function (url_launcher).
[https://github.com/flutter/flutter/issues/29976](url)

**Comment by rubberbird** [comment]
Thanks for checking.
